'use strict';

const test = require('node:test');
const assert = require('node:assert');
const path = require('node:path');
const fs = require('node:fs');
const { execFileSync } = require('node:child_process');
const { parseSafeJSON, runInit } = require('../lib/init');
const { version: CAR_VERSION } = require('../package.json');

test('parseSafeJSON: parses standard JSON', () => {
  const json = '{"a": 1, "b": "hello"}';
  const result = parseSafeJSON(json);
  assert.deepStrictEqual(result, { a: 1, b: 'hello' });
});

test('parseSafeJSON: strips single line comments', () => {
  const json = `{
    // This is a comment
    "a": 1,
    "b": "http://google.com" // another comment
  }`;
  const result = parseSafeJSON(json);
  assert.deepStrictEqual(result, { a: 1, b: 'http://google.com' });
});

test('parseSafeJSON: strips multi line comments', () => {
  const json = `{
    /* This is a
       multi-line comment */
    "a": 1
  }`;
  const result = parseSafeJSON(json);
  assert.deepStrictEqual(result, { a: 1 });
});

test('parseSafeJSON: handles empty or invalid json safely', () => {
  assert.deepStrictEqual(parseSafeJSON(''), {});
  assert.deepStrictEqual(parseSafeJSON('   '), {});
  assert.throws(() => parseSafeJSON('{"a": }'), SyntaxError);
});

test('runInit: scaffolds windsurf and cline adapters', async (t) => {
  const tmpDir = path.join(__dirname, 'tmp-init-project-' + Date.now());
  fs.mkdirSync(tmpDir, { recursive: true });

  t.after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  await runInit(tmpDir, {
    yes: true,
    tools: 'windsurf,cline',
    name: 'ScaffoldTest',
    force: true
  });

  assert.ok(fs.existsSync(path.join(tmpDir, 'AGENTS.md')), 'AGENTS.md should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'guardrails.md')), 'guardrails.md should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'guardrails.json')), 'guardrails.json should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.windsurfrules')), '.windsurfrules should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.clinerules')), '.clinerules should exist');

  const windsurfContent = fs.readFileSync(path.join(tmpDir, '.windsurfrules'), 'utf8');
  assert.match(windsurfContent, /Windsurf rules — ScaffoldTest/);

  const clineContent = fs.readFileSync(path.join(tmpDir, '.clinerules'), 'utf8');
  assert.match(clineContent, /Cline rules — ScaffoldTest/);
});

test('runInit: scaffolds git pre-commit hook when requested', async (t) => {
  const tmpDir = path.join(__dirname, 'tmp-git-project-' + Date.now());
  fs.mkdirSync(tmpDir, { recursive: true });

  t.after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  await runInit(tmpDir, {
    yes: true,
    tools: 'git',
    name: 'GitHookTest',
    git: true,
    force: true
  });

  assert.ok(fs.existsSync(path.join(tmpDir, 'AGENTS.md')), 'AGENTS.md should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.git', 'hooks', 'pre-commit')), 'Git pre-commit hook should exist');

  const hookContent = fs.readFileSync(path.join(tmpDir, '.git', 'hooks', 'pre-commit'), 'utf8');
  assert.match(hookContent, /Git pre-commit hook generated by create-agent-room/);

  const ciWorkflowPath = path.join(tmpDir, '.github', 'workflows', 'agent-room-validate.yml');
  assert.ok(fs.existsSync(ciWorkflowPath), 'CI workflow should exist');

  const ciWorkflowContent = fs.readFileSync(ciWorkflowPath, 'utf8');
  assert.match(ciWorkflowContent, new RegExp(`create-agent-room@${CAR_VERSION} validate`));
  assert.match(ciWorkflowContent, new RegExp(`create-agent-room@${CAR_VERSION} lint-sessions`));
  assert.doesNotMatch(ciWorkflowContent, /create-agent-room@latest/);
});

test('runInit: creates a clean initial commit when --git is passed (regression: guardrails must not block the tool\'s own genesis commit)', async (t) => {
  const tmpDir = path.join(__dirname, 'tmp-genesis-commit-' + Date.now());
  fs.mkdirSync(tmpDir, { recursive: true });

  t.after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  await runInit(tmpDir, {
    yes: true,
    tools: 'git',
    name: 'GenesisCommitTest',
    git: true,
    force: true
  });

  // The .github/workflows/** path is protected by the default guardrails
  // template, and the scaffold creates a workflow file under it. The
  // initial commit must still succeed cleanly (not be silently skipped).
  const status = execFileSync('git', ['status', '--porcelain'], { cwd: tmpDir, encoding: 'utf8' });
  assert.strictEqual(status.trim(), '', 'working tree should be clean after a successful initial commit');

  const log = execFileSync('git', ['log', '--oneline'], { cwd: tmpDir, encoding: 'utf8' });
  assert.match(log, /Scaffold project with create-agent-room/);

  const committedFiles = execFileSync('git', ['show', '--stat', '--name-only', 'HEAD'], {
    cwd: tmpDir,
    encoding: 'utf8'
  });
  assert.match(committedFiles, /\.github\/workflows\/agent-room-validate\.yml/);
});

test('runInit: scaffolds with custom parameters and optional skill packs', async (t) => {
  const tmpDir = path.join(__dirname, 'tmp-custom-project-' + Date.now());
  fs.mkdirSync(tmpDir, { recursive: true });

  t.after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  await runInit(tmpDir, {
    yes: true,
    tools: 'cursor',
    name: 'CustomTest',
    language: 'python',
    'package-manager': 'pipenv',
    branch: 'develop',
    'skill-packs': 'testing,security,code-review,api-design,database,performance,observability,documentation',
    force: true
  });

  // The python stack override (templates/stacks/python/AGENTS.md.tmpl) fully
  // replaces the generic base AGENTS.md.tmpl for this language, so assert
  // against its actual Python-specific content rather than the base template's.
  const agentsContent = fs.readFileSync(path.join(tmpDir, 'AGENTS.md'), 'utf8');
  assert.match(agentsContent, /\(Python\)/);
  assert.match(agentsContent, /PEP 8 compliance/);
  assert.match(agentsContent, /Package Manager.*pipenv/);
  assert.match(agentsContent, /Test Command.*pipenv run pytest/);
  assert.match(agentsContent, /Lint Command.*pipenv run flake8 \./);

  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room.json')), '.agent-room.json should exist');
  const config = JSON.parse(fs.readFileSync(path.join(tmpDir, '.agent-room.json'), 'utf8'));
  assert.strictEqual(config.language, 'python');
  assert.strictEqual(config.packageManager, 'pipenv');
  assert.strictEqual(config.defaultBranch, 'develop');
  assert.deepStrictEqual(config.skillPacks, ['testing', 'security', 'code-review', 'api-design', 'database', 'performance', 'observability', 'documentation']);

  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'integration-testing.md')), 'integration-testing skill should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'security-principles.md')), 'security-principles skill should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'code-review.md')), 'code-review skill should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'api-design.md')), 'api-design skill should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'database-migrations.md')), 'database-migrations skill should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'performance-optimization.md')), 'performance-optimization skill should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'observability.md')), 'observability skill should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'documentation.md')), 'documentation skill should exist');
  assert.ok(!fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'release-management.md')), 'release-management skill should NOT exist');
});

test('runInit: packaged templates/stacks/python override is actually used for --language python', async (t) => {
  // Regression test: templates/ (the real packaged template root, not a
  // synthetic fixture) has AGENTS.md.tmpl at its root plus a stacks/
  // subdirectory, with no base/ subdirectory. getLayers() must still treat
  // it as structured so templates/stacks/python/AGENTS.md.tmpl is picked up
  // instead of silently falling back to the generic root template.
  const tmpDir = path.join(__dirname, 'tmp-packaged-python-' + Date.now());
  fs.mkdirSync(tmpDir, { recursive: true });

  t.after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  await runInit(tmpDir, {
    yes: true,
    tools: 'none',
    name: 'PackagedPythonTest',
    language: 'python',
    force: true
  });

  const agentsContent = fs.readFileSync(path.join(tmpDir, 'AGENTS.md'), 'utf8');
  assert.match(agentsContent, /PEP 8 compliance/, 'AGENTS.md should contain Python-specific content, not the generic base template');
  assert.match(agentsContent, /Virtual Environment/, 'AGENTS.md should contain Python-specific content, not the generic base template');
});

const { detectWorkspace } = require('../lib/init');

test('detectWorkspace: detects Cargo.toml correctly', () => {
  const tmpDir = path.join(__dirname, 'tmp-detect-rust-' + Date.now());
  fs.mkdirSync(tmpDir, { recursive: true });
  fs.writeFileSync(path.join(tmpDir, 'Cargo.toml'), '[package]');

  const detected = detectWorkspace(tmpDir);
  assert.strictEqual(detected.language, 'rust');
  assert.strictEqual(detected.packageManager, 'cargo');

  fs.rmSync(tmpDir, { recursive: true, force: true });
});

test('detectWorkspace: detects package.json and tsconfig.json correctly', () => {
  const tmpDir = path.join(__dirname, 'tmp-detect-js-' + Date.now());
  fs.mkdirSync(tmpDir, { recursive: true });
  fs.writeFileSync(path.join(tmpDir, 'package.json'), '{}');
  fs.writeFileSync(path.join(tmpDir, 'tsconfig.json'), '{}');
  fs.writeFileSync(path.join(tmpDir, 'pnpm-lock.yaml'), '');

  const detected = detectWorkspace(tmpDir);
  assert.strictEqual(detected.language, 'typescript');
  assert.strictEqual(detected.packageManager, 'pnpm');

  fs.rmSync(tmpDir, { recursive: true, force: true });
});

test('runInit: rolls back created files on scaffolding failure', async (t) => {
  const tmpDir = path.join(__dirname, 'tmp-rollback-project-' + Date.now());
  fs.mkdirSync(tmpDir, { recursive: true });

  // Create "docs" as a file so that folder creation fails
  fs.writeFileSync(path.join(tmpDir, 'docs'), 'I am a file');

  t.after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  await assert.rejects(async () => {
    await runInit(tmpDir, {
      yes: true,
      tools: 'none',
      name: 'RollbackTest',
      force: true
    });
  });

  assert.strictEqual(fs.existsSync(path.join(tmpDir, 'AGENTS.md')), false, 'AGENTS.md should have been deleted during rollback');
  assert.strictEqual(fs.existsSync(path.join(tmpDir, '.agent-room', 'principles.md')), false, '.agent-room/principles.md should have been deleted during rollback');
});

test('runInit: template inheritance layers merge correctly', async (t) => {
  const tmpDir = path.join(__dirname, 'tmp-inheritance-' + Date.now());
  const tmplDir = path.join(__dirname, 'tmp-templates-' + Date.now());

  t.after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    fs.rmSync(tmplDir, { recursive: true, force: true });
  });

  // Setup structured template hierarchy
  fs.mkdirSync(path.join(tmplDir, 'base', '.agent-room'), { recursive: true });
  fs.mkdirSync(path.join(tmplDir, 'stacks', 'python', '.agent-room'), { recursive: true });
  fs.mkdirSync(path.join(tmplDir, 'org', 'acme', '.agent-room', 'skills'), { recursive: true });

  fs.writeFileSync(path.join(tmplDir, 'base', 'AGENTS.md.tmpl'), 'Base Agent {{PROJECT_NAME}}');
  fs.writeFileSync(path.join(tmplDir, 'base', '.agent-room', 'principles.md'), 'Base Principle');
  fs.writeFileSync(path.join(tmplDir, 'stacks', 'python', '.agent-room', 'principles.md'), 'Python Principle');
  fs.writeFileSync(path.join(tmplDir, 'org', 'acme', '.agent-room', 'principles.md'), 'Acme Principle');
  fs.writeFileSync(path.join(tmplDir, 'org', 'acme', '.agent-room', 'skills', 'acme-skill.md'), 'Acme Skill');

  fs.mkdirSync(tmpDir, { recursive: true });

  await runInit(tmpDir, {
    yes: true,
    tools: 'none',
    name: 'InheritTest',
    language: 'python',
    org: 'acme',
    'template-source': tmplDir,
    force: true
  });

  // Verify Base layer file was copied
  assert.ok(fs.existsSync(path.join(tmpDir, 'AGENTS.md')), 'AGENTS.md should exist');
  assert.strictEqual(fs.readFileSync(path.join(tmpDir, 'AGENTS.md'), 'utf8'), 'Base Agent InheritTest');

  // Verify Principles file was overridden by Acme org (highest priority)
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'principles.md')), 'principles.md should exist');
  assert.strictEqual(fs.readFileSync(path.join(tmpDir, '.agent-room', 'principles.md'), 'utf8'), 'Acme Principle');

  // Verify Acme specific skill was copied
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'acme-skill.md')), 'acme-skill.md should exist');
  assert.strictEqual(fs.readFileSync(path.join(tmpDir, '.agent-room', 'skills', 'acme-skill.md'), 'utf8'), 'Acme Skill');
});

test('runInit: resolves local external skill pack correctly', async (t) => {
  const tmpDir = path.join(__dirname, 'tmp-ext-init-' + Date.now());
  const extDir = path.join(__dirname, 'tmp-ext-skills-' + Date.now());

  t.after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    fs.rmSync(extDir, { recursive: true, force: true });
  });

  // Setup external skill packs dir
  fs.mkdirSync(extDir, { recursive: true });
  fs.writeFileSync(path.join(extDir, 'my-custom-rule.md'), 'Custom Rule {{PROJECT_NAME}}');
  fs.writeFileSync(path.join(extDir, 'README.md'), 'Should be skipped');

  fs.mkdirSync(tmpDir, { recursive: true });

  await runInit(tmpDir, {
    yes: true,
    tools: 'none',
    name: 'ExtTest',
    'skill-packs': `testing,${extDir}`,
    force: true
  });

  // Verify built-in skill pack was copied
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'integration-testing.md')), 'integration-testing skill should exist');

  // Verify local external skill was copied and rendered with vars
  assert.ok(fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'my-custom-rule.md')), 'my-custom-rule.md should exist');
  assert.strictEqual(fs.readFileSync(path.join(tmpDir, '.agent-room', 'skills', 'my-custom-rule.md'), 'utf8'), 'Custom Rule ExtTest');

  // Verify README.md was skipped
  assert.ok(!fs.existsSync(path.join(tmpDir, '.agent-room', 'skills', 'README.md')), 'README.md should be skipped');
});


