'use strict';

const test = require('node:test');
const assert = require('node:assert');
const path = require('node:path');
const fs = require('node:fs');
const { parseSafeJSON, runInit } = require('../lib/init');

test('parseSafeJSON: parses standard JSON', () => {
  const json = '{"a": 1, "b": "hello"}';
  const result = parseSafeJSON(json);
  assert.deepStrictEqual(result, { a: 1, b: 'hello' });
});

test('parseSafeJSON: strips single line comments', () => {
  const json = `{
    // This is a comment
    "a": 1,
    "b": "http://google.com" // another comment
  }`;
  const result = parseSafeJSON(json);
  assert.deepStrictEqual(result, { a: 1, b: 'http://google.com' });
});

test('parseSafeJSON: strips multi line comments', () => {
  const json = `{
    /* This is a
       multi-line comment */
    "a": 1
  }`;
  const result = parseSafeJSON(json);
  assert.deepStrictEqual(result, { a: 1 });
});

test('parseSafeJSON: handles empty or invalid json safely', () => {
  assert.deepStrictEqual(parseSafeJSON(''), {});
  assert.deepStrictEqual(parseSafeJSON('   '), {});
  assert.throws(() => parseSafeJSON('{"a": }'), SyntaxError);
});

test('runInit: scaffolds windsurf and cline adapters', async (t) => {
  const tmpDir = path.join(__dirname, 'tmp-init-project-' + Date.now());
  fs.mkdirSync(tmpDir, { recursive: true });

  t.after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  await runInit(tmpDir, {
    yes: true,
    tools: 'windsurf,cline',
    name: 'ScaffoldTest',
    force: true
  });

  assert.ok(fs.existsSync(path.join(tmpDir, 'AGENTS.md')), 'AGENTS.md should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.windsurfrules')), '.windsurfrules should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.clinerules')), '.clinerules should exist');

  const windsurfContent = fs.readFileSync(path.join(tmpDir, '.windsurfrules'), 'utf8');
  assert.match(windsurfContent, /Windsurf rules — ScaffoldTest/);

  const clineContent = fs.readFileSync(path.join(tmpDir, '.clinerules'), 'utf8');
  assert.match(clineContent, /Cline rules — ScaffoldTest/);
});

test('runInit: scaffolds git pre-commit hook when requested', async (t) => {
  const tmpDir = path.join(__dirname, 'tmp-git-project-' + Date.now());
  fs.mkdirSync(tmpDir, { recursive: true });

  t.after(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  await runInit(tmpDir, {
    yes: true,
    tools: 'git',
    name: 'GitHookTest',
    git: true,
    force: true
  });

  assert.ok(fs.existsSync(path.join(tmpDir, 'AGENTS.md')), 'AGENTS.md should exist');
  assert.ok(fs.existsSync(path.join(tmpDir, '.git', 'hooks', 'pre-commit')), 'Git pre-commit hook should exist');

  const hookContent = fs.readFileSync(path.join(tmpDir, '.git', 'hooks', 'pre-commit'), 'utf8');
  assert.match(hookContent, /Git pre-commit hook generated by create-agent-room/);
});
