'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { bold, green, red, yellow, cyan, gray } = require('./color');

const SUPPORTED_HOOKS = [
  'pre-commit',
  'pre-push',
  'post-commit',
  'post-checkout',
  'post-merge',
];

const PACKAGED_TEMPLATES_DIR = path.join(__dirname, '..', 'templates');

function resolveHooksDir(target) {
  target = target || '.';
  let hooksPath = null;
  try {
    hooksPath = execFileSync('git', ['config', 'core.hooksPath'], {
      cwd: target,
      stdio: ['ignore', 'pipe', 'ignore'],
      encoding: 'utf8',
    }).trim();
  } catch (e) {
    // ignore git config error
  }

  if (hooksPath) {
    return path.isAbsolute(hooksPath) ? hooksPath : path.join(target, hooksPath);
  }

  const dotGit = path.join(target, '.git');
  if (fs.existsSync(dotGit)) {
    try {
      const stat = fs.statSync(dotGit);
      if (stat.isDirectory()) {
        return path.join(dotGit, 'hooks');
      }
      // git worktree or submodule where .git is a file containing "gitdir: ..."
      const content = fs.readFileSync(dotGit, 'utf8').trim();
      const match = content.match(/^gitdir:\s*(.+)$/i);
      if (match) {
        const gitDir = path.isAbsolute(match[1]) ? match[1] : path.resolve(target, match[1]);
        return path.join(gitDir, 'hooks');
      }
    } catch (e) {
      // ignore
    }
  }

  return path.join(target, '.git', 'hooks');
}

function getHookTemplate(hookName, options) {
  options = options || {};
  let tmplFile;
  if (options.templateDir) {
    tmplFile = path.join(options.templateDir, 'adapters', 'git-hooks', `${hookName}.tmpl`);
  }
  if (!tmplFile || !fs.existsSync(tmplFile)) {
    tmplFile = path.join(PACKAGED_TEMPLATES_DIR, 'adapters', 'git-hooks', `${hookName}.tmpl`);
  }
  if (!fs.existsSync(tmplFile)) {
    throw new Error(`Template not found for git hook: "${hookName}"`);
  }
  const content = fs.readFileSync(tmplFile, 'utf8');
  // Strip shebang line if present
  const lines = content.split('\n');
  if (lines[0] && lines[0].startsWith('#!')) {
    lines.shift();
  }
  return lines.join('\n').trim();
}

function getStartMarker(hookName) {
  return `# --- create-agent-room hook: ${hookName} ---`;
}

function getEndMarker(hookName) {
  return `# --- end create-agent-room hook: ${hookName} ---`;
}

function buildHookBlock(hookName, bodyContent) {
  return `${getStartMarker(hookName)}\n${bodyContent.trim()}\n${getEndMarker(hookName)}`;
}

function getHookBlockRegex(hookName) {
  const start = getStartMarker(hookName).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const end = getEndMarker(hookName).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`(?:\\r?\\n)?${start}[\\s\\S]*?${end}(?:\\r?\\n)?`, 'g');
}

function isLegacyCarHook(content, hookName) {
  if (hookName === 'pre-commit') {
    return (
      content.includes('.agent-room/hooks/guardrails-check.js') ||
      content.includes('Git pre-commit hook generated by create-agent-room')
    );
  }
  return false;
}

function isExecutable(filePath) {
  if (process.platform === 'win32') return true;
  try {
    const stat = fs.statSync(filePath);
    return (stat.mode & 0o111) !== 0;
  } catch (e) {
    return false;
  }
}

function setExecutable(filePath) {
  try {
    fs.chmodSync(filePath, 0o755);
  } catch (e) {
    // ignore on platforms where chmod is unsupported
  }
}

function normalizeHookList(input) {
  if (!input) return [];
  if (Array.isArray(input)) return input.map((h) => String(h).trim().toLowerCase());
  return String(input)
    .split(',')
    .map((h) => h.trim().toLowerCase())
    .filter(Boolean);
}

function installHooks(target, options) {
  options = options || {};
  target = target || '.';

  const dotGit = path.join(target, '.git');
  if (!fs.existsSync(dotGit) && !options.force) {
    return {
      ok: false,
      error: `Target "${target}" is not a git repository (.git not found). Pass --force to install anyway.`,
      results: [],
    };
  }

  let requested = normalizeHookList(options.hooks || options.hook);
  if (options.all) {
    requested = [...SUPPORTED_HOOKS];
  } else if (requested.length === 0) {
    // Default hook to install
    requested = ['pre-commit'];
  }

  // Validate hook names
  for (const name of requested) {
    if (!SUPPORTED_HOOKS.includes(name)) {
      return {
        ok: false,
        error: `Unknown hook: "${name}". Supported hooks are: ${SUPPORTED_HOOKS.join(', ')}`,
        results: [],
      };
    }
  }

  const hooksDir = resolveHooksDir(target);
  fs.mkdirSync(hooksDir, { recursive: true });

  const results = [];

  for (const hookName of requested) {
    const hookBody = getHookTemplate(hookName, options);
    const hookBlock = buildHookBlock(hookName, hookBody);
    const hookFile = path.join(hooksDir, hookName);

    if (fs.existsSync(hookFile)) {
      const existing = fs.readFileSync(hookFile, 'utf8');
      const startMarker = getStartMarker(hookName);

      if (existing.includes(startMarker)) {
        // Update existing block
        const regex = getHookBlockRegex(hookName);
        const updated = existing.replace(regex, `\n${hookBlock}\n`);
        fs.writeFileSync(hookFile, updated.trim() + '\n', 'utf8');
        setExecutable(hookFile);
        results.push({ hook: hookName, action: 'updated', path: hookFile, chained: true });
      } else if (isLegacyCarHook(existing, hookName)) {
        // Legacy standalone hook -> upgrade to delimited block
        const shebang = existing.startsWith('#!') ? existing.split('\n')[0] : '#!/bin/sh';
        const upgraded = `${shebang}\n\n${hookBlock}\n`;
        fs.writeFileSync(hookFile, upgraded, 'utf8');
        setExecutable(hookFile);
        results.push({ hook: hookName, action: 'upgraded', path: hookFile, chained: false });
      } else {
        // Chained install: append to existing script
        const separator = existing.endsWith('\n') ? '\n' : '\n\n';
        const appended = existing + separator + hookBlock + '\n';
        fs.writeFileSync(hookFile, appended, 'utf8');
        setExecutable(hookFile);
        results.push({ hook: hookName, action: 'chained', path: hookFile, chained: true });
      }
    } else {
      // Fresh install
      const freshContent = `#!/bin/sh\n\n${hookBlock}\n`;
      fs.writeFileSync(hookFile, freshContent, 'utf8');
      setExecutable(hookFile);
      results.push({ hook: hookName, action: 'created', path: hookFile, chained: false });
    }
  }

  // If pre-commit was installed or target has an .agent-room directory, ensure guardrails-check.js is present
  if (requested.includes('pre-commit') || fs.existsSync(path.join(target, '.agent-room'))) {
    const hooksDest = path.join(target, '.agent-room', 'hooks');
    const guardrailScript = path.join(hooksDest, 'guardrails-check.js');
    if (!fs.existsSync(guardrailScript)) {
      const srcTmpl = path.join(PACKAGED_TEMPLATES_DIR, 'adapters', 'git-hooks', 'guardrails-check.js');
      if (fs.existsSync(srcTmpl)) {
        fs.mkdirSync(hooksDest, { recursive: true });
        fs.copyFileSync(srcTmpl, guardrailScript);
        setExecutable(guardrailScript);
      }
    }
  }

  return {
    ok: true,
    hooksDir,
    results,
  };
}

function getHookStatus(target, _options) {
  target = target || '.';

  const hooksDir = resolveHooksDir(target);
  const statusList = [];

  for (const hookName of SUPPORTED_HOOKS) {
    const hookFile = path.join(hooksDir, hookName);
    const exists = fs.existsSync(hookFile);

    if (!exists) {
      statusList.push({
        hook: hookName,
        path: hookFile,
        installed: false,
        active: false,
        executable: false,
        chained: false,
        drifted: false,
      });
      continue;
    }

    const content = fs.readFileSync(hookFile, 'utf8');
    const hasBlock = content.includes(getStartMarker(hookName));
    const isLegacy = isLegacyCarHook(content, hookName);
    const installed = hasBlock || isLegacy;
    const executable = isExecutable(hookFile);
    const active = installed && executable;

    let chained = false;
    let drifted = false;

    if (hasBlock) {
      // Check if there is non-whitespace content outside the CAR block
      const stripped = content.replace(getHookBlockRegex(hookName), '').replace(/^#![^\n]*/, '').trim();
      chained = stripped.length > 0;

      // Check drift against current template
      try {
        const expectedBody = getHookTemplate(hookName).trim();
        const start = getStartMarker(hookName);
        const end = getEndMarker(hookName);
        const startIdx = content.indexOf(start);
        const endIdx = content.indexOf(end);
        if (startIdx !== -1 && endIdx !== -1) {
          const currentBody = content.substring(startIdx + start.length, endIdx).trim();
          drifted = currentBody !== expectedBody;
        }
      } catch (e) {
        // ignore
      }
    } else if (isLegacy) {
      try {
        const tmplFile = path.join(PACKAGED_TEMPLATES_DIR, 'adapters', 'git-hooks', `${hookName}.tmpl`);
        if (fs.existsSync(tmplFile)) {
          const fullTemplate = fs.readFileSync(tmplFile, 'utf8');
          drifted = content.replace(/\r\n/g, '\n').trim() !== fullTemplate.replace(/\r\n/g, '\n').trim();
        } else {
          drifted = true;
        }
      } catch (e) {
        drifted = true;
      }
    }

    statusList.push({
      hook: hookName,
      path: hookFile,
      installed,
      active,
      executable,
      chained,
      drifted,
      isLegacy,
    });
  }

  return {
    ok: true,
    hooksDir,
    hooks: statusList,
    summary: {
      total: SUPPORTED_HOOKS.length,
      installed: statusList.filter((s) => s.installed).length,
      active: statusList.filter((s) => s.active).length,
      drifted: statusList.filter((s) => s.drifted).length,
    },
  };
}

function uninstallHooks(target, options) {
  options = options || {};
  target = target || '.';

  const hooksDir = resolveHooksDir(target);
  let requested = normalizeHookList(options.hooks || options.hook);

  if (options.all || requested.length === 0) {
    requested = [...SUPPORTED_HOOKS];
  }

  const results = [];

  for (const hookName of requested) {
    const hookFile = path.join(hooksDir, hookName);
    if (!fs.existsSync(hookFile)) {
      results.push({ hook: hookName, action: 'skipped', path: hookFile, reason: 'not_found' });
      continue;
    }

    const content = fs.readFileSync(hookFile, 'utf8');
    const hasBlock = content.includes(getStartMarker(hookName));
    const isLegacy = isLegacyCarHook(content, hookName);

    if (!hasBlock && !isLegacy) {
      results.push({ hook: hookName, action: 'skipped', path: hookFile, reason: 'not_car_hook' });
      continue;
    }

    if (hasBlock) {
      // Remove delimited block
      const stripped = content.replace(getHookBlockRegex(hookName), '');
      // Check if anything meaningful remains
      const remainingCode = stripped.replace(/^#![^\n]*/, '').replace(/#.*$/gm, '').trim();

      if (remainingCode.length === 0) {
        // No user code remains, delete file
        fs.unlinkSync(hookFile);
        results.push({ hook: hookName, action: 'deleted', path: hookFile });
      } else {
        // User code remains, preserve file without CAR block
        fs.writeFileSync(hookFile, stripped.trim() + '\n', 'utf8');
        setExecutable(hookFile);
        results.push({ hook: hookName, action: 'unhooked', path: hookFile });
      }
    } else if (isLegacy) {
      // Legacy CAR hook -> check if other commands exist
      const lines = content.split('\n').filter((l) => !l.startsWith('#') && l.trim().length > 0);
      const isOnlyCar = lines.every((l) => l.includes('.agent-room') || l.includes('node') || l.includes('exit'));
      if (isOnlyCar) {
        fs.unlinkSync(hookFile);
        results.push({ hook: hookName, action: 'deleted', path: hookFile });
      } else {
        results.push({ hook: hookName, action: 'skipped', path: hookFile, reason: 'legacy_requires_manual_edit' });
      }
    }
  }

  return {
    ok: true,
    hooksDir,
    results,
  };
}

function runHookCli(target, action, args, options) {
  options = options || {};
  target = target || '.';
  action = (action || 'status').toLowerCase();

  if (action === 'status' || action === 'list' || action === 'ls') {
    const statusData = getHookStatus(target, options);

    if (options.json || options.format === 'json') {
      console.log(JSON.stringify(statusData, null, 2));
      return 0;
    }

    console.log(bold('\ncreate-agent-room Git Hooks Status'));
    console.log(gray(`Directory: ${statusData.hooksDir}\n`));

    console.log('Hook            Status       Executable  Chained  Notes');
    console.log('--------------  -----------  ----------  -------  ----------------------');

    for (const item of statusData.hooks) {
      const nameCol = item.hook.padEnd(14);
      let statusCol;
      if (item.active) {
        statusCol = green('Active     ');
      } else if (item.installed && !item.executable) {
        statusCol = yellow('No-Exec    ');
      } else {
        statusCol = gray('Not Found  ');
      }

      const execCol = (item.executable ? green('Yes       ') : gray('No        ')).padEnd(10);
      const chainCol = (item.chained ? cyan('Yes    ') : gray('No     ')).padEnd(7);

      let notes = '';
      if (item.drifted) notes = yellow('⚠️  Drifted from template');
      else if (item.active && item.chained) notes = cyan('Preserves user scripts');
      else if (item.active) notes = green('✓ Managed by CAR');

      console.log(`${nameCol}  ${statusCol}  ${execCol}  ${chainCol}  ${notes}`);
    }

    console.log(
      `\nSummary: ${statusData.summary.active} active, ${statusData.summary.installed} installed, ${statusData.summary.drifted} drifted (${statusData.summary.total} total supported)\n`
    );
    return 0;
  }

  if (action === 'install' || action === 'add' || action === 'setup') {
    const res = installHooks(target, options);
    if (!res.ok) {
      console.error(red(`\n❌ Error: ${res.error}\n`));
      return 1;
    }

    if (options.json || options.format === 'json') {
      console.log(JSON.stringify(res, null, 2));
      return 0;
    }

    console.log(bold('\n✅ Git Hooks Installed Successfully!'));
    console.log(gray(`Target directory: ${res.hooksDir}\n`));

    for (const r of res.results) {
      const hookLabel = cyan(r.hook.padEnd(14));
      if (r.action === 'created') {
        console.log(`  ${green('created')}  ${hookLabel} (standalone executable hook)`);
      } else if (r.action === 'chained') {
        console.log(`  ${green('chained')}  ${hookLabel} (appended to existing user hook)`);
      } else if (r.action === 'updated') {
        console.log(`  ${green('updated')}  ${hookLabel} (updated existing CAR block)`);
      } else if (r.action === 'upgraded') {
        console.log(`  ${green('upgraded')} ${hookLabel} (migrated legacy CAR hook)`);
      }
    }
    console.log(gray('\nRun "create-agent-room hook status" to inspect all hooks.\n'));
    return 0;
  }

  if (action === 'uninstall' || action === 'remove' || action === 'rm') {
    const res = uninstallHooks(target, options);
    if (!res.ok) {
      console.error(red(`\n❌ Error: ${res.error}\n`));
      return 1;
    }

    if (options.json || options.format === 'json') {
      console.log(JSON.stringify(res, null, 2));
      return 0;
    }

    console.log(bold('\n🧹 Git Hooks Uninstalled!'));
    console.log(gray(`Target directory: ${res.hooksDir}\n`));

    for (const r of res.results) {
      const hookLabel = cyan(r.hook.padEnd(14));
      if (r.action === 'deleted') {
        console.log(`  ${yellow('deleted')}    ${hookLabel} (file removed; contained only CAR block)`);
      } else if (r.action === 'unhooked') {
        console.log(`  ${green('unhooked')}   ${hookLabel} (CAR block removed; user scripts preserved)`);
      } else if (r.action === 'skipped') {
        console.log(`  ${gray('skipped')}    ${hookLabel} (${r.reason})`);
      }
    }
    console.log('');
    return 0;
  }

  if (action === 'pre-push' || (action === 'run' && args && args[0] === 'pre-push')) {
    const remote = (action === 'pre-push' ? args && args[0] : args && args[1]) || options.remote || 'origin';
    const opts = Object.assign({}, options, { remote });
    return runPrePushCli(target, opts);
  }

  console.error(red(`\nUnknown hook action: "${action}". Valid actions: install, status, uninstall, pre-push\n`));
  return 1;
}

function detectUpstreamBranch(target, remoteName) {
  target = target || '.';
  remoteName = remoteName || 'origin';

  if (process.env.CAR_BASE_REF) {
    return process.env.CAR_BASE_REF.trim();
  }

  // Check .agent-room.json prePush.base
  const configPath = path.join(target, '.agent-room.json');
  if (fs.existsSync(configPath)) {
    try {
      const cfg = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      if (cfg && cfg.hooks && cfg.hooks.prePush && typeof cfg.hooks.prePush.base === 'string') {
        return cfg.hooks.prePush.base.trim();
      }
    } catch (e) {
      // ignore
    }
  }

  // Try upstream tracking branch
  try {
    const upstream = execFileSync('git', ['rev-parse', '--abbrev-ref', '@{upstream}'], {
      cwd: target,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    if (upstream && upstream !== '@{upstream}') {
      return upstream;
    }
  } catch (e) {
    // ignore
  }

  // Try remote main/master verification
  try {
    execFileSync('git', ['rev-parse', '--verify', `${remoteName}/main`], {
      cwd: target,
      stdio: 'ignore',
    });
    return `${remoteName}/main`;
  } catch (e) {
    // ignore
  }

  try {
    execFileSync('git', ['rev-parse', '--verify', `${remoteName}/master`], {
      cwd: target,
      stdio: 'ignore',
    });
    return `${remoteName}/master`;
  } catch (e) {
    // ignore
  }

  try {
    execFileSync('git', ['rev-parse', '--verify', 'origin/main'], {
      cwd: target,
      stdio: 'ignore',
    });
    return 'origin/main';
  } catch (e) {
    // ignore
  }

  try {
    execFileSync('git', ['rev-parse', '--verify', 'origin/master'], {
      cwd: target,
      stdio: 'ignore',
    });
    return 'origin/master';
  } catch (e) {
    // ignore
  }

  // Fallback to defaultBranch from .agent-room.json or origin/main
  if (fs.existsSync(configPath)) {
    try {
      const cfg = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      if (cfg && cfg.defaultBranch) {
        return `${remoteName}/${cfg.defaultBranch}`;
      }
    } catch (e) {
      // ignore
    }
  }

  return `${remoteName}/main`;
}

function resolvePrePushConfig(target, remoteName) {
  target = target || '.';
  remoteName = remoteName || 'origin';

  let prePush = {};
  const configPath = path.join(target, '.agent-room.json');
  if (fs.existsSync(configPath)) {
    try {
      const cfg = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      if (cfg && cfg.hooks && typeof cfg.hooks.prePush === 'object') {
        prePush = cfg.hooks.prePush;
      }
    } catch (e) {
      // ignore
    }
  }

  const enabled = prePush.enabled !== false;
  const strict = Boolean(prePush.strict);
  const skip = Array.isArray(prePush.skip)
    ? prePush.skip
    : prePush.skip
    ? String(prePush.skip).split(',').map((s) => s.trim()).filter(Boolean)
    : [];
  const only = Array.isArray(prePush.only)
    ? prePush.only
    : prePush.only
    ? String(prePush.only).split(',').map((s) => s.trim()).filter(Boolean)
    : [];
  const base =
    (typeof prePush.base === 'string' && prePush.base.trim()) ||
    (process.env.CAR_BASE_REF && process.env.CAR_BASE_REF.trim()) ||
    detectUpstreamBranch(target, remoteName);

  return {
    enabled,
    strict,
    skip,
    only,
    base,
  };
}

function runPrePush(target, options) {
  options = options || {};
  target = target || '.';

  // 1. Check bypass env vars
  if (
    process.env.CAR_SKIP_HOOK === '1' ||
    process.env.CAR_SKIP_PRE_PUSH === '1' ||
    options.skipHook ||
    options.skipPrePush
  ) {
    return {
      ok: true,
      skipped: true,
      reason: 'bypassed via environment variable',
      report: null,
    };
  }

  // 2. Check branch deletions if stdin was provided
  const stdin = options.stdin || '';
  if (stdin.trim()) {
    const lines = stdin.trim().split('\n');
    const z40 = '0000000000000000000000000000000000000000';
    let hasCommits = false;
    for (const line of lines) {
      const parts = line.trim().split(/\s+/);
      if (parts.length >= 2 && parts[1] !== z40 && parts[1] !== '') {
        hasCommits = true;
        break;
      }
    }
    if (!hasCommits && lines.length > 0) {
      return {
        ok: true,
        skipped: true,
        reason: 'branch-deletion',
        report: null,
      };
    }
  }

  // 3. Resolve config
  const config = resolvePrePushConfig(target, options.remote);
  if (!config.enabled) {
    return {
      ok: true,
      skipped: true,
      reason: 'prePush hook disabled in .agent-room.json',
      report: null,
    };
  }

  // 4. Construct CI options
  const { runCi } = require('./ci');
  let effectiveBase = options.base || config.base;
  if (effectiveBase) {
    try {
      execFileSync('git', ['rev-parse', '--verify', effectiveBase], {
        cwd: target,
        stdio: 'ignore',
      });
    } catch (e) {
      effectiveBase = null;
    }
  }

  const ciOptions = {
    base: effectiveBase,
    strict: options.strict !== undefined ? options.strict : config.strict,
    skip: options.skip || config.skip,
    only: options.only || config.only,
  };

  const report = runCi(target, ciOptions);
  return {
    ok: report.ok,
    skipped: false,
    baseRef: ciOptions.base,
    report,
  };
}

function runPrePushCli(target, options) {
  options = options || {};
  target = target || '.';

  const res = runPrePush(target, options);

  if (res.skipped) {
    if (options.json || options.format === 'json') {
      console.log(JSON.stringify(res, null, 2));
    }
    return 0;
  }

  const { formatCiReport } = require('./ci');
  if (options.json || options.format === 'json') {
    console.log(JSON.stringify(res, null, 2));
  } else if (res.report) {
    console.log(formatCiReport(res.report, 'text'));
  }

  if (!res.ok) {
    console.error(red('\n❌ create-agent-room: Pre-push compliance checks failed.\n'));
    console.error('Remediation:');
    console.error('  - Fix failing tests, unapproved rule weakening, or missing session logs shown above.');
    console.error(`  - Run checks manually: create-agent-room ci --base ${res.baseRef}`);
    console.error('  - To bypass for emergency pushes:');
    console.error('      git push --no-verify');
    console.error('    or:');
    console.error('      CAR_SKIP_PRE_PUSH=1 git push\n');
    return 1;
  }

  return 0;
}

module.exports = {
  SUPPORTED_HOOKS,
  resolveHooksDir,
  getHookTemplate,
  buildHookBlock,
  getHookBlockRegex,
  getStartMarker,
  getEndMarker,
  installHooks,
  getHookStatus,
  uninstallHooks,
  detectUpstreamBranch,
  resolvePrePushConfig,
  runPrePush,
  runPrePushCli,
  runHookCli,
};
